// <auto-generated />
namespace Movie_Booking.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class price : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(price));
        
        string IMigrationMetadata.Id
        {
            get { return "202211171621317_price"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
