// <auto-generated />
namespace Movie_Booking.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class trailer : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(trailer));
        
        string IMigrationMetadata.Id
        {
            get { return "202211182113406_trailer"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
